=== alexandrev/SonarQube-Plugin-for-BusinessWorks6/sonar-businessworks6-plugin/src/main/resources/org/sonar/plugins/tibco/bw/profiles/qualityProfile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by Alexandre (XANDREV) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="Profile">
        <xs:annotation>
            <xs:documentation>Comment describing your root element</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Data">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Version" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Elements">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ModuleProperty" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="NamingPattern" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Resources" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="LocationPattern" type="xs:string"/>
                                        <xs:element name="Resource" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="NamingPattern" type="xs:string"/>
                                                    <xs:element name="Type" type="xs:string"/>            
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Process" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="NamingPattern" type="xs:string"/>
                                        <xs:element name="LocationPattern" type="xs:string"/>
                                        <xs:element name="ProcessProperty" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="NamingPattern" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Activities" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="NamingPattern" type="xs:string"/>
                                                    <xs:element name="Type" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Descriptors" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="NamingPattern" type="xs:string"/>
                                        <xs:element name="LocationPattern" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Schemas" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="NamingPattern" type="xs:string"/>
                                        <xs:element name="LocationPattern" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== alexandrev/SonarQube-Plugin-for-BusinessWorks6/sonar-businessworks6-plugin/src/main/resources/org/sonar/plugins/tibco/bw/profiles/profile.default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 (http://www.altova.com)-->
<Profile xsi:noNamespaceSchemaLocation="qualityProfile.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Data>
        <Name>DEFAULT</Name>
        <Version>1.0</Version>
    </Data>
    <Elements>
        <ModuleProperty>
            <NamingPattern>.*</NamingPattern>
        </ModuleProperty>
        <Resources>
            <LocationPattern>Resources/.*</LocationPattern>
            <Resource>
                <NamingPattern>.*</NamingPattern>
                <Type>JMSConnection</Type>
            </Resource>
        </Resources>
        <Process>
            <NamingPattern>.*</NamingPattern>
            <LocationPattern>Processes/.*</LocationPattern>
        </Process>
        <Descriptors>
            <NamingPattern>.*</NamingPattern>
            <LocationPattern>Service Descriptors/.*</LocationPattern>
        </Descriptors>
        <Schemas>
            <NamingPattern>.*</NamingPattern>
            <LocationPattern>Schemas/.*</LocationPattern>
        </Schemas>
    </Elements>
</Profile>
